/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscribeTemplate: typeof import('./src/components/SubscribeTemplate.vue')['default']
    SubscribeUser: typeof import('./src/components/SubscribeUser.vue')['default']
  }
}
